image: texlive/texlive:latest


stages:
  - build

pdf:
  stage: build
  script:
    - apt install latexmk -y
    - apt install gnuplot -y
    - pdflatex main.tex
    - makeindex main.nlo -s nomencl.ist -o main.nls
    - latexmk -pdf -f main.tex
  artifacts:
    paths:
      - main.pdf
    expire_in: 1 day
