image: texlive/texlive:latest


stages:
  - build

pdf:
  stage: build
  script:
    - apt install latexmk
    - latexmk -pdf -f main.tex
  artifacts:
    paths:
      - main.pdf
    expire_in: 1 day
